name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_AU }}
        password: ${{ secrets.REGISTRY_AP }}
        registry: ${{ secrets.REGISTRY_A }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{secrets.REGISTRY_A}}/custom-errors:latest
